# General
name: Minimal-Block
description: "Minimalistic, friendly, responsive."
url: https://coetzeer.github.io/jekyll-theme-minimal-block/

markdown: kramdown
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: drvy
twitter: drvymonkey
github: drvy
google: +DrvyMonkey

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

gems:
  - jekyll-paginate